[project]
name = "file-uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.4.2",
    "loguru>=0.7.2",
    "pcloud>=1.3",
    "pillow>=11.0.0",
    "questionary>=2.0.1",
]
